### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by rxverse** [Bansaidnes/temp#2]
how to install pls help, I cannot send to my friend on discord it say file size too big

**Comment by Bansaidnes** [comment]
Simple fix, stop being poor. Buy nitro. 


Hope this solution helps :)!

**Comment by rxverse** [comment]
can I get free nitro plz

**Comment by Bansaidnes** [comment]
Sorry, I do not run a  charity. Please return to picking cotton.

**Comment by SemiConductorShortage** [comment]
> Sorry, I do not run a charity. Please return to picking cotton.

Reported and cancelled
